name = "aw-api"
main = "src/index.ts"
compatibility_date = "2024-10-01"

# workers.dev URL-এ চলবে। কাস্টম ডোমেইন পরে যোগ করতে পারো।

[[d1_databases]]
binding = "DB"              # env.DB
database_name = "aw_db"
database_id = "8059b80c-7ebc-4bb0-92f0-919721858178"  # ড্যাশবোর্ড/CLI থেকে বসাবে

[[kv_namespaces]]
binding = "PROMPTS"         # env.PROMPTS
id = "111bddb0d86a44e2a099fc069e980f67"

[[r2_buckets]]
binding = "R2"              # env.R2
bucket_name = "aw-releases"
